// Project configuration, loaded from ProjectSettings.json.
//
// Precedence: code defaults < ProjectSettings.json < command line. The command line always wins so
// that switching backends for a quick test never requires editing the file.
//
// Every setting is consumed once, during FEngine::Initialize, when the window and device are created.
// None of them is applied to a running session: changing one means editing the file and restarting.
// That keeps the running configuration immutable, so anything reading it cannot observe a value the
// engine is not actually using.

#pragma once

#include "Core/Json/JsonUtils.h"
#include "RHI/RHITypes.h"

#include <filesystem>
#include <string>
#include <string_view>

namespace Lime
{
	// Debug runtimes cost performance, so the default follows the build configuration.
	enum class EValidationMode : uint8
	{
		Off = 0,
		DebugOnly,
		On
	};

	struct FProjectSettings
	{
		std::string ProjectName = "LimeProject";

		std::string WindowTitle = "LimeEngine";
		uint32 WindowWidth = 1600;
		uint32 WindowHeight = 900;

		ERHIBackend Backend = GetDefaultBackend();
		uint32 BackBufferCount = 3;
		bool bVSync = true;
		EValidationMode Validation = EValidationMode::DebugOnly;

		bool bEnableEditor = LIME_WITH_EDITOR != 0;

		// Local automation server. Enabled by default in debug builds only: it exposes engine state
		// over a loopback socket, which belongs in development rather than in a shipped build.
		bool bEnableAutomation = LIME_DEBUG != 0;
		uint32 AutomationPort = 5613;

		// glTF file to load at startup. Empty means the project runs without a scene, which is a valid
		// configuration rather than an error: a project may draw entirely through its own passes.
		//
		// Relative paths are resolved against the project directory and then the shared Assets directory,
		// so a settings file can reference the sample assets without an absolute path.
		std::string ScenePath;
		// Vertical field of view in degrees. Degrees rather than radians because this is hand edited.
		float CameraFieldOfView = 60.0f;
		// Units per second the fly camera moves at before any scroll adjustment.
		float CameraMoveSpeed = 3.0f;
		// Multiplies the directional light. Zero leaves the scene lit by ambient alone.
		float LightIntensity = 3.0f;
		// Flat term standing in for bounced light, so faces turned away from the light are not pure black.
		float AmbientStrength = 0.25f;

		// <exe>/ProjectSettings.json, falling back to the source tree during development.
		static std::filesystem::path ResolveSettingsPath();
		// The file inside the project source tree, which is the one worth editing: the copy beside the
		// executable is regenerated by every build. Empty in installed builds.
		static std::filesystem::path ResolveAuthoringPath();

		// Applies the file on top of the current values. Missing or malformed entries are reported
		// and left at their defaults, so a broken file degrades instead of preventing startup.
		bool LoadFromFile(const std::filesystem::path& Path);

		// Rewrites only the keys this struct owns, so comments elsewhere and keys added by future
		// versions survive. Writes the authoring copy in the source tree and, when it exists, refreshes
		// the copy next to the executable so a restart picks the change up without rebuilding.
		// Returns false and logs when nothing could be written.
		bool SaveToFile() const;

		// Supported switches: --rhi=<d3d12|vulkan>, --width=N, --height=N, --no-editor, --no-vsync,
		// --validation=<off|debugOnly|on>, --project=<path to json>, --automation, --no-automation,
		// --automation-port=N.
		void ApplyCommandLine(int ArgumentCount, const char* const* Arguments);

		// Serializes into the same schema LoadFromFile reads, so a client sees exactly the keys it can
		// write back.
		FJson ToJson() const;
		// Applies a partial object of the same shape. Reports the first offending key through OutError
		// and leaves every field untouched in that case, so a bad request cannot half apply.
		bool ApplyJson(const FJson& Json, std::string& OutError);

		bool IsValidationEnabled() const;
		void LogSummary() const;

		// True when every field matches, used by the editor to track unsaved changes.
		bool operator==(const FProjectSettings& Other) const;
		bool operator!=(const FProjectSettings& Other) const { return !(*this == Other); }
	};

	const char* ToString(EValidationMode Mode);
	bool TryParseValidation(std::string_view Text, EValidationMode& OutMode);
} // namespace Lime
