// Project configuration, loaded from ProjectSettings.json.
//
// Precedence: code defaults < ProjectSettings.json < command line. The command line always wins so
// that switching backends for a quick test never requires editing the file.

#pragma once

#include "Core/Json/JsonUtils.h"
#include "RHI/RHITypes.h"

#include <filesystem>
#include <string>
#include <string_view>

namespace Lime
{
	// Debug runtimes cost performance, so the default follows the build configuration.
	enum class EValidationMode : uint8
	{
		Off = 0,
		DebugOnly,
		On
	};

	struct FProjectSettings
	{
		std::string ProjectName = "LimeProject";

		std::string WindowTitle = "LimeEngine";
		uint32 WindowWidth = 1600;
		uint32 WindowHeight = 900;

		ERHIBackend Backend = GetDefaultBackend();
		uint32 BackBufferCount = 3;
		bool bVSync = true;
		EValidationMode Validation = EValidationMode::DebugOnly;

		bool bEnableEditor = LIME_WITH_EDITOR != 0;
		// Writes pass settings to Saved/ on exit and restores them on start. Off by default, because
		// stale saved values silently override changes made to the defaults in code.
		bool bPersistPassSettings = false;

		// Local automation server. Enabled by default in debug builds only: it exposes engine state
		// over a loopback socket, which belongs in development rather than in a shipped build.
		bool bEnableAutomation = LIME_DEBUG != 0;
		uint32 AutomationPort = 5613;

		// <exe>/ProjectSettings.json, falling back to the source tree during development.
		static std::filesystem::path ResolveSettingsPath();
		// The file inside the project source tree, which is the one worth editing: the copy beside the
		// executable is regenerated by every build. Empty in installed builds.
		static std::filesystem::path ResolveAuthoringPath();

		// Applies the file on top of the current values. Missing or malformed entries are reported
		// and left at their defaults, so a broken file degrades instead of preventing startup.
		bool LoadFromFile(const std::filesystem::path& Path);

		// Rewrites only the keys this struct owns, so comments elsewhere and keys added by future
		// versions survive. Writes the authoring copy in the source tree and, when it exists, refreshes
		// the copy next to the executable so a restart picks the change up without rebuilding.
		// Returns false and logs when nothing could be written.
		bool SaveToFile() const;

		// Supported switches: --rhi=<d3d12|vulkan>, --width=N, --height=N, --no-editor, --no-vsync,
		// --validation=<off|debugOnly|on>, --project=<path to json>, --automation, --no-automation,
		// --automation-port=N.
		void ApplyCommandLine(int ArgumentCount, const char* const* Arguments);

		// Serializes into the same schema LoadFromFile reads, so a client sees exactly the keys it can
		// write back.
		FJson ToJson() const;
		// Applies a partial object of the same shape. Reports the first offending key through OutError
		// and leaves every field untouched in that case, so a bad request cannot half apply.
		bool ApplyJson(const FJson& Json, std::string& OutError);

		bool IsValidationEnabled() const;
		void LogSummary() const;

		// True when every field matches, used by the editor to track unsaved changes.
		bool operator==(const FProjectSettings& Other) const;
		bool operator!=(const FProjectSettings& Other) const { return !(*this == Other); }
	};

	const char* ToString(EValidationMode Mode);
	bool TryParseValidation(std::string_view Text, EValidationMode& OutMode);
} // namespace Lime
