# Regenerates the MSVC include paths in .clangd.
#
# Why .clangd needs them: compile_commands.json records the cl.exe command line but not the MSVC and
# Windows SDK include directories, because cl.exe reads those from the INCLUDE environment variable that
# vcvars sets. clangd only inherits INCLUDE if the editor itself was started from a developer
# environment, which is not something to rely on. Without those paths the first #include fails and every
# type in the file is reported as unknown.
#
# Run this after a Visual Studio or Windows SDK update, or when setting the project up on a new machine.

[CmdletBinding()]
param(
	# Reports the paths without writing the file.
	[switch]$WhatIfOnly
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot
$ConfigPath = Join-Path $RepoRoot '.clangd'

# EnterDevShell resolves the toolset and populates INCLUDE, which is exactly the list needed here.
& (Join-Path $PSScriptRoot 'EnterDevShell.ps1')

if (-not $env:INCLUDE)
{
	throw 'INCLUDE is not set after loading the developer environment.'
}

# -imsvc rather than -isystem: the compile command names cl.exe, so clangd runs in clang-cl driver mode,
# where -isystem is not recognised and is silently ignored.
$Flags = ($env:INCLUDE -split ';' | Where-Object { $_ } | ForEach-Object {
	$Normalised = $_.TrimEnd('\').Replace('\', '/') -replace '/+', '/'
	"    - `"-imsvc$Normalised`""
}) -join "`n"

Write-Host 'MSVC include paths:' -ForegroundColor Cyan
$Flags -split "`n" | ForEach-Object { Write-Host "  $($_.Trim())" }

$Content = @"
# clangd configuration. Generated by Scripts/UpdateClangdConfig.ps1; edit that script rather than the
# lists below, and rerun it after a Visual Studio or Windows SDK update.
#
# Two things are set here, and both are needed.
#
# CompilationDatabase points at the build tree. clangd otherwise looks only in the workspace root and
# a "build" subdirectory, finds nothing, and falls back to guessed flags -- which is why headers report
# their own includes as missing. An editor setting can pass --compile-commands-dir instead, but not
# every editor forwards clangd.arguments reliably, so stating it in the config is the dependable route.
#
# CompileFlags.Add supplies the MSVC and Windows SDK include paths. compile_commands.json records the
# cl.exe command line but not those directories, because cl.exe reads them from the INCLUDE environment
# variable that vcvars sets. clangd does not inherit INCLUDE unless the editor was started from a
# developer environment, and without it the first #include fails and every type becomes unknown.
#
# The flag is -imsvc, not -isystem: the compile command names cl.exe, so clangd runs in clang-cl driver
# mode, where -isystem is not recognised and is silently ignored.

CompileFlags:
  CompilationDatabase: Build/ninja
  Add:
$Flags

Index:
  # Indexes the whole project so go-to-definition and find-references reach across files instead of
  # working only inside the open one. Set here rather than through --background-index for the same
  # reason as the compilation database: editor arguments are not always forwarded.
  Background: Build

Diagnostics:
  # Missing and unused includes are the compiler's job, and clangd's guesses are noisy on a codebase
  # that relies on transitive includes from third party headers. The check list itself comes from
  # .clang-tidy, which clangd reads on its own.
  UnusedIncludes: None
  MissingIncludes: None

---
# Third party sources are indexed so navigation reaches into them, but not diagnosed: their warnings
# are not actionable here and would bury the project's own.
If:
  PathMatch: ThirdParty/.*
Diagnostics:
  Suppress: "*"
"@

if ($WhatIfOnly)
{
	Write-Host "`nDry run; .clangd was not written." -ForegroundColor Yellow
	exit 0
}

# No BOM: clangd's YAML parser rejects it.
[System.IO.File]::WriteAllText($ConfigPath, $Content, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "`nWrote $ConfigPath" -ForegroundColor Green
Write-Host 'Restart the editor, or run "clangd: Restart language server" from the command palette.' -ForegroundColor Cyan
