// Editor appearance, loaded from EditorSettings.json.
//
// Kept in the Editor module rather than beside FProjectSettings, because nothing outside the editor
// reads it: a build with LIME_BUILD_EDITOR off would carry configuration it can never apply.
//
// Like FProjectSettings, every value is consumed once, when FEditorLayer initializes. None of them is
// applied to a running session, so what the editor shows always matches what it was started with.
// The reason is not that a live update is impossible, but that it would make the running appearance
// and the file disagree until the next save.
//
// The file is separate from ProjectSettings.json rather than a section inside it, so a project can
// keep engine configuration and editor appearance apart, and so a missing file simply means defaults.

#pragma once

#include "Core/Json/JsonUtils.h"
#include "Core/Math/Vector.h"

#include <filesystem>
#include <string>
#include <string_view>

namespace Lime
{
	// Base palettes ImGui ships. The accent colour is applied on top of whichever is chosen, so a
	// project can keep a familiar palette and still brand it.
	enum class EEditorTheme : uint8
	{
		Dark = 0,
		Light,
		Classic
	};

	struct FEditorSettings
	{
		// ImGui's own default is 20; smaller reads better on the dense panels the editor uses.
		// Bounds are enforced on load: a font too small to read or large enough to break the dock
		// layout is a configuration mistake rather than a preference.
		static constexpr float MinFontSize = 8.0f;
		static constexpr float MaxFontSize = 48.0f;
		static constexpr float DefaultFontSize = 16.0f;

		float FontSize = DefaultFontSize;
		EEditorTheme Theme = EEditorTheme::Dark;
		// Tints interactive widgets: check marks, slider grabs, selected tabs. Stored as RGB in the
		// 0..1 range; alpha is not configurable because these are opaque by construction.
		FVector3 AccentColor = DefaultAccentColor();

		static constexpr FVector3 DefaultAccentColor() { return { 0.56f, 0.83f, 0.35f }; }

		// <exe>/EditorSettings.json, falling back to the source tree during development.
		static std::filesystem::path ResolveSettingsPath();
		// The file inside the project source tree, which is the one worth editing: the copy beside
		// the executable is regenerated by every build. Empty in installed builds.
		static std::filesystem::path ResolveAuthoringPath();

		// Applies the file on top of the current values. A missing file is not an error: the defaults
		// are a complete configuration, so a project only writes one when it wants something else.
		// Malformed entries are reported and left at their defaults.
		bool LoadFromFile(const std::filesystem::path& Path);

		// Rewrites only the keys this struct owns, so comments and keys added by future versions
		// survive. Writes the authoring copy and refreshes the deployed one, matching
		// FProjectSettings::SaveToFile so both panels behave the same way.
		bool SaveToFile() const;

		FJson ToJson() const;
		// Applies a partial object of the same shape. Reports the first offending key through
		// OutError and leaves every field untouched in that case, so a bad request cannot half apply.
		bool ApplyJson(const FJson& Json, std::string& OutError);

		void LogSummary() const;

		bool operator==(const FEditorSettings& Other) const;
		bool operator!=(const FEditorSettings& Other) const { return !(*this == Other); }
	};

	const char* ToString(EEditorTheme Theme);
	bool TryParseEditorTheme(std::string_view Text, EEditorTheme& OutTheme);
} // namespace Lime
